### ISSUE TITLE
Getting a grpc.health.v1.Health/Check error when I first try the import script

### ISSUE THREAD

**Issue by weisisheng** [weaviate/quote-finder#2]
New to the latest typescript client.  I've got a remote weaviate instance (now 1.24.5) behind a caddy container manager which I have been running for a few years.  Can curl a query without a problem.  The weaviate container has both 80/50051 ports mapped to from caddy. AFAIKT, I've got the typescript config set up correctly.  I should mention, I've got a salted api key for the caddy setup.  No problems accessing with earlier scripts, apps written in typescript.

Appreciate any tip or tricks for the below:

When I try either the example import script or a simple health check, I get the error, "  

npx tsx ./sample.ts

node:internal/process/esm_loader:46
      internalBinding('errors').triggerUncaughtException(
                                ^
ClientError: /grpc.health.v1.Health/Check UNAVAILABLE: No connection established. Last error: 0048303E2E7F0000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1586:SSL alert number 80
 (2024-04-13T00:40:55.082Z)
    at wrapClientError (/home/vfulco/weaviate-world/hybrid-search-example-20240413/backend/node_modules/nice-grpc/src/client/wrapClientError.ts:7:12)
    at Object.callback (/home/vfulco/weaviate-world/hybrid-search-example-20240413/backend/node_modules/nice-grpc/src/client/createUnaryMethod.ts:63:35)
    at Object.onReceiveStatus (/home/vfulco/weaviate-world/hybrid-search-example-20240413/backend/node_modules/@grpc/grpc-js/src/client.ts:360:26)
    at Object.onReceiveStatus (/home/vfulco/weaviate-world/hybrid-search-example-20240413/backend/node_modules/@grpc/grpc-js/src/client-interceptors.ts:458:34)
    at Object.onReceiveStatus (/home/vfulco/weaviate-world/hybrid-search-example-20240413/backend/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
    at <anonymous> (/home/vfulco/weaviate-world/hybrid-search-example-20240413/backend/node_modules/@grpc/grpc-js/src/resolving-call.ts:132:24)
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:449:9) {
  path: '/grpc.health.v1.Health/Check',
  code: 14,
  details: 'No connection established. Last error: 0048303E2E7F0000:error:0A000438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1586:SSL alert number 80\n' +
    ' (2024-04-13T00:40:55.082Z)'
}

Node.js v20.5.1

**Comment by weisisheng** [comment]
Switched to WCS for now to speed up dev, fix later.
